dataset_module: 'dataset'
dataset_class: 'KptrajReconShapeDataset'
module: 'traj_sh.traj_recon_shape_cvae' 
model: 'TrajReconShape'

dataset_inputs:
  num_steps: 40
  wpt_dim: 6
  sample_num_points: 1000
  enable_traj: 1
  enable_affordance: 0
  enable_partseg: 0
  
model_inputs:
  pcd_feat_dim: 512
  traj_feat_dim: 128
  hidden_dim: 128
  z_feat_dim: 128 # not used
  num_steps: 40
  wpt_dim: 6
  lbd_kl: 0.1
  lbd_recon: 1.0
  kl_annealing: 0

lr: 0.001
lr_decay_rate: 0.95
lr_decay_epoch: 1000
weight_decay: 0.0001
save_freq: 2000

batch_size: 16

start_epoch: 0
stop_epoch: 30000