dataset_module: 'dataset_tdn_seg'
dataset_class: 'KptrajDeformAffordanceDataset'
enable_affordance: 1
module: 'traj_deform.traj_deform_fusion_lstm_seg_v2' 
model: 'TrajDeformFusionLSTM'

dataset_inputs:
  num_steps: 10
  wpt_dim: 3
  sample_num_points: 1000
  with_noise: 1
  gt_trajs: 20
  with_afford_score: 1
  
model_inputs:
  pcd_feat_dim: 128
  wpt_feat_dim: 128
  hidden_dim: 256
  num_steps: 10
  wpt_dim: 3
  decoder_layers: 2
  lbd_cls: 0.1
  lbd_dir: 1.0
  lbd_deform: 1.0
  gt_trajs: 20
  with_afford_score: 1

lr: 0.0001
lr_decay_rate: 0.95
lr_decay_epoch: 100
weight_decay: 0.0001
save_freq: 100

batch_size: 192

start_epoch: 0
stop_epoch: 5000