dataset_module: 'dataset'
dataset_class: 'KptrajReconAffordanceDataset'
enable_affordance: 1
module: 'traj_recon_affordance_nofp_4d_cvae_nn_dist_mr' 
model: 'TrajReconAffordanceNoFP4D'

dataset_inputs:
  num_steps: 10
  wpt_dim: 6
  sample_num_points: 1000
  enable_traj: 1
  affordance_type: 0
  
model_inputs:
  pcd_feat_dim: 128
  traj_feat_dim: 128
  # cp_feat_dim: 32 # no this feature
  hidden_dim: 128
  z_feat_dim: 128 
  num_steps: 10
  wpt_dim: 6
  lbd_kl: 0.1
  lbd_recon: 1.0
  lbd_dir: 10.0
  kl_annealing: 0

lr: 0.0001
lr_decay_rate: 0.95
lr_decay_epoch: 1000
weight_decay: 0.0001
save_freq: 2000

batch_size: 16

start_epoch: 0
stop_epoch: 30000