dataset_module: 'dataset'
dataset_class: 'KptrajReconShapeDataset'
module: 'traj_recon_shape_cae' 
model: 'TrajReconShape'

inputs:
  pcd_feat_dim: 512
  traj_feat_dim: 256
  z_feat_dim: 256 # not used
  num_steps: 30
  lbd_kl: 1.0
  lbd_recon: 1.0
  lbd_dir: 1.0

lr: 0.001
lr_decay_rate: 0.9
lr_decay_epoch: 2
weight_decay: 0.0001
save_freq: 20

batch_size: 16

start_epoch: 0
stop_epoch: 200