==============================================================================================================================================
checkpoint: "checkpoints/traj_recon_affordance_cvae_kl_large_03.04.18.36_nn/hook_all_new_0-kptraj_all_new_0-absolute-40_02.27.10.29-1000/30000"
dataset: "../dataset/traj_recon_affordance/hook_all_new_0-kptraj_all_new_0-absolute-40/02.27.10.29-1000"
result:
    description: 
        1. the waypoint is too close to the object, noisy, too short
    suggestion: 
        1. decrease the weight of nearest neighbor loss
note: 
    1. use nearest neighbor loss
config: 
    dataset_module: 'dataset'
    dataset_class: 'KptrajReconAffordanceDataset'
    enable_affordance: 1
    module: 'traj_recon_affordance_cvae' 
    model: 'TrajReconAffordance'

    dataset_inputs:
    num_steps: 40
    wpt_dim: 6
    sample_num_points: 1000
    enable_traj: 1
    affordance_type: 0
    
    model_inputs:
    pcd_feat_dim: 128
    traj_feat_dim: 128
    cp_feat_dim: 32
    hidden_dim: 128
    z_feat_dim: 128 
    num_steps: 40
    wpt_dim: 6
    lbd_kl: 0.1
    lbd_recon: 1.0
    lbd_dir: 10.0
    kl_annealing: 0

    lr: 0.0001
    lr_decay_rate: 0.95
    lr_decay_epoch: 1000
    weight_decay: 0.0001
    save_freq: 2000

    batch_size: 16

    start_epoch: 0
    stop_epoch: 30000

==============================================================================================================================================
checkpoint: "checkpoints/traj_recon_affordance_cvae_kl_large_03.05.13.57_nn-mr/hook_all_new_0-kptraj_all_new_0-absolute-40_02.27.10.29-1000/30000"
dataset: "../dataset/traj_recon_affordance/hook_all_new_0-kptraj_all_new_0-absolute-40/02.27.10.29-1000"
result:
    description: 
        1. the waypoint is too close to the object, noisy, too short
    suggestion: 
        1. decrease the weight of nearest neighbor loss
note: 
    1. use nearest neighbor loss
    2. use weighted reconstruction loss
config: 
    dataset_module: 'dataset'
    dataset_class: 'KptrajReconAffordanceDataset'
    enable_affordance: 1
    module: 'traj_recon_affordance_cvae' 
    model: 'TrajReconAffordance'

    dataset_inputs:
    num_steps: 40
    wpt_dim: 6
    sample_num_points: 1000
    enable_traj: 1
    affordance_type: 0
    
    model_inputs:
    pcd_feat_dim: 128
    traj_feat_dim: 128
    cp_feat_dim: 32
    hidden_dim: 128
    z_feat_dim: 128 
    num_steps: 40
    wpt_dim: 6
    lbd_kl: 0.1
    lbd_recon: 1.0
    lbd_dir: 10.0
    kl_annealing: 0

    lr: 0.0001
    lr_decay_rate: 0.95
    lr_decay_epoch: 1000
    weight_decay: 0.0001
    save_freq: 2000

    batch_size: 16

    start_epoch: 0
    stop_epoch: 30000